### PR TITLE
Fix: rewrite dialog service

### LINKED ISSUE #8: Last jN 2.2.185.2 and Wrap With Abbreviation generate error
After update jN to last version I get error when second time invoke  `Wrap With Abbreviation`, first time works correct (show dialog box) but next time always throw.
Error info:
`'handle.document' jest pusty lub nie jest obiektem
line: 128, pos: 7`
It came from `jN\includes\emmet.js`.
When I back to previous jN 2.1.181 version (from 2016) problem not exist.

Platform detial:
Windows7 64-bit
Notepad++ 7.5.5 32-bit
jN 2.2.185.2
jN-npp-emmet 1.1.2

### PR DESCRIPTION
**Pull request by eight04**
Fixes #8.

### CODE REVIEW

File: dist/emmet.js [hunk 1]
```diff
@@ -98,139 +98,145 @@
...
+   *  * html: dialog innerHTML.
+   *  * onresolve: resolve handler.
+   *  * onreject: reject handler.
+   */
+  function createDialog(options) {
+    var destroyed = false;
+    
+    var htmlDialog = System.createDialog({
+      onbeforeclose: function() {
+        if (!destroyed) {
```
Comment (eight04) [inline dist/emmet.js]: Add some comment "Overwrite the behavior of top right x button".
